### PR TITLE
Allow to override build date with SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by bmwiedemann**
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

Without this patch, the `epics-base` package varied in html docs
for every build.

This PR was done while working on reproducible builds for openSUSE.

### CODE REVIEW

**Comment by khwilliamson** [comment]
Karen, this looks good to me, but I would like a more expert opinion.

**Comment by karenetheridge** [comment]
looks good, but can we name the environment variable `PERL_POD_SIMPLE_SOURCE_DATE_EPOCH` to make it abundantly clear who the consumer of this variable is intended to be?

**Comment by bmwiedemann** [comment]
Renaming the variable would be bad, because `SOURCE_DATE_EPOCH` is a standard name already consumed by dozens of other tools and to make this reproducible then would need packagers to discover and use this special variable.

**Comment by karenetheridge** [comment]
> `SOURCE_DATE_EPOCH` is a standard name already consumed by dozens of other tools

Ah I see; good to know!

**Comment by khwilliamson** [comment]
How soon do you need a release

**Comment by bmwiedemann** [comment]
It is not urgent. reproducible-builds is a long-term project, so if this ends up in perl in 2021, that will be fine.

**Pull request merged**
