### PR TITLE
Remove Sub::Util dependency

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by karenetheridge** [comment]
What is the impact of removing prototypes here?

**Comment by atoomic** [comment]
@karenetheridge indeed at the same time I removed Sub::Util, I've not restored the default prototypes, which I think is your complain. I'm not sure of any issues with that, at first glance the test suite is clean on all Perl versions smoked.

Of course it's not going to throw errors when the function is called incorrectly.
But honestly all the files changed there are part of the test suite, which is the reason why I think it's fine.

If you are aware about any limitations or concern about this change, please let me know.

**Comment by karenetheridge** [comment]
I am wondering why the tests took the trouble to set the prototypes in the first place.

**Comment by atoomic** [comment]
I agree with you... they probably never really needed prototype, and this was probably considered a good practice at one point... that source code is pretty old

**Pull request merged**
