### PR TITLE
`.travis.yml`: Delete

### LINKED ISSUE #170: `.travis.yml`: Is Travis CI used?
Since there's a `testsuite.yml` file for GH Actions too.

If not anymore, can I remove it (seems confusing and there's no link to check the results)?

Thanks

### PR DESCRIPTION
**Pull request by rwp0**
Travis CI is no longer used

GitHub Actions replaces that

Fixes #170

### CODE REVIEW

**Comment by rwp0** [comment]
Trivia: couldn't create PR via IntelliJ IDEA due to OAuth third-party restrictions.

Resorted to GitHub web for that.

**Comment by rwp0** [comment]
@haarg requesting your review

**Review by haarg — APPROVED** [review]

**Review by rwp0 — COMMENTED** [review]
I'll remove the line from `MANIFEST.SKIP` as well

**Comment by rwp0** [comment]
Removed the line from `MANIFEST.SKIP`:
image
@khwilliamson please consider merging now

**Pull request merged**
