### PR TITLE
suppress "UTF-16 surrogate 0xd800" warning

### LINKED ISSUE #113: Pod::Simple::BlackBox emits a warning "UTF-16 surrogate 0xd800"
Pod::Simple::BlackBox emits a warning on perl 5.8.x:
```
UTF-16 surrogate 0xd800 at /Users/skaji/env/plenv/versions/5.8.9/lib/perl5/site_perl/5.8.9/Pod/Simple/BlackBox.pm line 67.
```
Especially, we often see the warning through Module::Build:
```
❯ perl -v
This is perl, v5.8.9 built for darwin-2level

❯ wget https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-Pretty-0.32.tar.gz

❯ tar xzf Test-Pretty-0.32.tar.gz

❯ cd Test-Pretty-0.32

❯ perl Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Test-Pretty' version '0.32'
cp META.json MYMETA.json
cp META.yml MYMETA.yml

❯ ./Build
Building Test-Pretty
UTF-16 surrogate 0xd800 at /Users/skaji/env/plenv/versions/5.8.9/lib/perl5/site_perl/5.8.9/Pod/Simple/BlackBox.pm line 67.
```

It is nice Pod::Simple::BlackBox suppresses this warning.

### PR DESCRIPTION
**Pull request by skaji**
Fix #113

### CODE REVIEW

**Comment by khwilliamson** [comment]
It was my fault, and your fix is correct.  How soon do you need this module released with this fix?

**Comment by skaji** [comment]
@khwilliamson  It's not urgent.
Thank you for merging PR!

**Comment by khwilliamson** [comment]
On 11/26/19 7:05 PM, Shoichi Kaji wrote:
> @khwilliamson <https://github.com/khwilliamson> It's not urgent.
> Thank you for merging PR!
> 

I just released a version, and this is the first fix awaiting a new 
release, so my temptation is to wait a while and see what else shows up. 
  Prod me if it is getting too long for you.

**Comment by DabeDotCom** [comment]
Hi,

I just wanted to note that I ran into this recently, as well, on an older box running Perl 5.10 (e.g., CentOS 6)

I do agree with @skaji, though, that it's still not "urgent"; I just patched the module *in situ*, and moved on with my life!  ;-D

However, if I might offer the ***tiniest*** bit of feedback — what I typically refer to as *"Going from an 'A' to an 'A+'"*...

In the same way that you [wisely] chose to limit the SCOPE of the `no warnings` with the `do {}` block, I might also consider limiting the CATEGORY as well, by suppressing only `no warnings 'utf8'` ***just*** in case some other type of message ever crops up.  «shrug»

(Or you might [equally wisely] say, "Eh, silence is golden...  Disabling ***all*** warnings, like it is now, will help make sure whiners like that @DabeDotCom guy never bother me again!"  Hehe)

PS — FWIW, I see that [Perl 5.14](https://perldoc.perl.org/perl5140delta.html#New-warnings-categories-for-problematic-(non-)Unicode-code-points.) also introduced `no warnings 'surrogate';` but using `utf8` is obviously more backwards-compatible...

PPS — For fun, though, and just to explore what would happen, I played around with trying to do something like:

```
eval { no warnings 'surrogate'; 1 } or eval { no warnings 'utf8'; 1 };
```

But that doesn't work because the former fails to compile *at all* on older versions, irrespective of whether or not it's inside an `eval` block...  So I tried `eval`-ing a *string* instead, to catch compilation errors:

```
eval "no warnings 'surrogate'; 1" or eval "no warnings 'utf8'; 1";
```

However, \*THAT* doesn't work either, because `warnings` is a **pragma**, and affects the **lexical** scope...  By the time the `eval` runs, it's too late, and it won't end up affecting subsequent statements, which have already been compiled...

***Unless*** you were to fold the `"\x{D800}"` \*ITSELF* into each `eval`-ed string!

```
# This is gross, and totally not worth it, and I'm a bad person for even thinking it!

my $cs_re = my_qr( '\p{IsCs}',    eval q{ no warnings 'surrogate'; "\x{D800}" }
                               || eval q{ no warnings 'utf8';      "\x{D800}" } );
```

🤮🤮🤮

And even \*THAT* probably doesn't Do The Right Thing anyway, since newer versions don't actually warn on the assignment; they warn on trying to, e.g., `say` a string *containing* a surrogate.

Ahh well, it was fun/educational for me anyway...  "Thank you for letting me share!"  ;-D

**Comment by jwrightecs** [comment]
When will this fix reach CPAN?

**Pull request merged**
